### ISSUE TITLE
HTTP 500 on scripting service.

### ISSUE THREAD

**Issue by carlduranleau** [elastos/Elastos.NET.Hive.JS.SDK#21]
There an HTTP 500 error returned by the scripting service :+1: 

```
   2021-10-15T01:41:12.896Z ERROR NodeRPCException (xf42igo)  Traceback (most recent call last):
      File "/src/src/utils/http_response.py", line 19, in wrapper
        return HiveException.get_success_response(func(self, *args, **kwargs),
      File "/src/src/modules/scripting/scripting.py", line 576, in run_script
        return Script(script_name, json_data, did, app_id, self.hive_setting, scripting=self).execute()
      File "/src/src/modules/scripting/scripting.py", line 522, in execute
        ret = executable.execute()
      File "/src/src/modules/scripting/scripting.py", line 342, in execute
        options = populate_options_find_many(self.body) if 'options' in self.body else {}
      File "/src/hive/util/did_mongo_db_resource.py", line 129, in populate_options_find_many
        "batch_size"))
      File "/src/hive/util/did_mongo_db_resource.py", line 39, in options_filter
        if arg in options:
    TypeError: argument of type 'NoneType' is not iterable

```

Request generating this error:

`    2021-10-15T01:41:12.849Z INFO HttpClient (wdk2v1s)  HTTP Request: PATCH http://localhost:9001/api/v2/vault/scripting/get_group_messages withAuthorization: true payload: {"context":{"target_did":"did:elastos:ifJkpmsjykgzT7XDyFo9cqwWYJiaWeTSxL","target_app_did":"did:elastos:iag8qwq1xPBpLsGv4zR4CmzLpLUkBNfPHX"},"params":{}}
`

The first hypothesis is that there are missing parameters in the request which are mandatory and it breaks the Hive Node service  when trying to loop through request options.

**Comment by carlduranleau** [comment]
Fixed by other updates
